SAFTETY Comments Ensure that automated install of share folder is only done after install/Setup of owncloud

diff --git a/webserver/owncloud b/webserver/owncloud
--- a/webserver/owncloud
+++ b/webserver/owncloud
@@ -25,25 +25,30 @@ install)
   ${COMMAND}
   RES=$?
   
-  # The script relies too much on fail fast and exit hard
-  # which is really bad so we temporarly disable this
-  set +eo pipefail
-  # TEMPORARY Permission hack 
-  chown root:root config/config.php
-  /var/www/owncloud/occ app:enable files_external
-  /var/www/owncloud/occ config:app:set core enable_external_storage --value=yes
-  chown -R www-data:www-data ${SHARED:-/shared/}
-  chmod -R 750 /mnt/data
-  # Create shared directory at /shared/ by default if not set
-  /var/www/owncloud/occ files_external:create -c "datadir=${SHARED:-/shared/Public}" /share/ local null::null 
-  /var/www/owncloud/occ files:scan --all 
-  chown www-data:www-data config/config.php
-  set -eo pipefail
 
   if [[ "${RES}" -ge "1" ]]; then
     exit ${RES}
   else
-    exit 0
+
+  # FOR the meme
+  # Evrything should be installed and should be okay to fail 
+  # We temporarly allow root to have read and write permission to ensure that we
+  # read and write to config.php
+  # UNSAFE {
+      set +eo pipefail
+      # TEMPORARY Permission hack 
+      chown root:root config/config.php
+      /var/www/owncloud/occ app:enable files_external
+      /var/www/owncloud/occ config:app:set core enable_external_storage --value=yes
+      chown -R www-data:www-data ${SHARED:-/shared/}
+      chmod -R 750 /mnt/data
+      # Create shared directory at /shared/ by default if not set
+      /var/www/owncloud/occ files_external:create -c "datadir=${SHARED:-/shared/Public}" /share/ local null::null 
+      /var/www/owncloud/occ files:scan --all 
+      chown www-data:www-data config/config.php
+      set -eo pipefail
+      exit 0
+    # }
   fi
   ;;
 migrate)
